### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by jlwatson00** [movestore/Add_Elevation#6]
<img width="1280" alt="error" src="https://user-images.githubusercontent.com/124986896/234664908-c7aac278-c923-4bf2-b2c0-37d20931cc95.png">
[Ferruginous Hawk sample.csv](https://github.com/movestore/Add_Elevation/files/11336043/Ferruginous.Hawk.sample.csv)

**Comment by andreakoelzsch** [comment]
Hi Jesse, I have run the App locally with your data and it runs through without any problems. So, I cannot reproduce the error and fix it. Please remind me, did you download the data from Movebank? If so, could you give me access to it there (andreakoelzsch) and share the workflow with me on MoveApps (andreakoelzsch) so that I can see what has gone wrong? Thanks a lot and good to meet you guys :) (sorry, I see only now that I have not tagged you on this: @jlwatson00 )
